#define Tutorial_VERSION_MAJOR  @Tutorial_VERSION_MAJOR@
#define Tutorial_VERSION_MINOR  @Tutorial_VERSION_MINOR@
#define CMAKE_CXX_FLAGS_DEBUG   "@CMAKE_CXX_FLAGS_DEBUG@"
#define CMAKE_CXX_FLAGS_RELEASE "@CMAKE_CXX_FLAGS_RELEASE@"
#define CMAKE_C_FLAGS_DEBUG     "@CMAKE_C_FLAGS_DEBUG@"
#define CMAKE_C_FLAGS_RELEASE   "@CMAKE_C_FLAGS_RELEASE@"
